### NumPy

NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. 

In [2]:
import numpy as np

## create array using numpy
arr1 = np.array([1,2,3,4,6])
print(arr1)
print(type(arr1))
print(arr1.shape) ## ---> 1-D array

[1 2 3 4 6]
<class 'numpy.ndarray'>
(5,)


In [3]:
arr2 = np.array([1,2,3,4,5,6])
arr2.reshape(2,3)       ## 2d array


array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
## identity matrix

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
arr = np.array([[1,2,3,4],[6,7,8,9]])

print("Array:\n",arr)
print("Shape: ",arr.shape)
print("number of dimension: ",arr.ndim)
print("size: ",arr.size)
print("data type: ",arr.dtype)
print("Item size: ", arr.itemsize)

Array:
 [[1 2 3 4]
 [6 7 8 9]]
Shape:  (2, 4)
number of dimension:  2
size:  8
data type:  int64
Item size:  8


In [ ]:
## vector operations

arr1 = np.array([3,4,5,6,7])
arr2 = np.array([10,20,30,40,50])

## element wise addition

print("Addition: ", arr1 + arr2)

## element wise subtraction
print("subtraction: ",arr2 - arr1)

## element wise multiplication

print("Multiplication: ",arr1 * arr2)


Addition:  [13 24 35 46 57]
subtraction:  [ 7 16 25 34 43]
Multiplication:  [ 30  80 150 240 350]


In [22]:
## Universal functions

arr = np.array([1,3,2,4,5])
## square root 
print(np.sqrt(arr))

# Exponential 
print(np.exp(arr))

## Sin
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.         1.73205081 1.41421356 2.         2.23606798]
[  2.71828183  20.08553692   7.3890561   54.59815003 148.4131591 ]
[ 0.84147098  0.14112001  0.90929743 -0.7568025  -0.95892427]
[0.         1.09861229 0.69314718 1.38629436 1.60943791]


In [57]:
## array slicing and indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
arr[0][1]

np.int64(2)

In [13]:
## 1: -> starts from row 1
## 2: --> starts from column 2
arr[1:,2:] ## [[ 7,  8],[11, 12]]

array([[ 7,  8],
       [11, 12]])

In [26]:
arr[0:2, 2:]

array([[3, 4],
       [7, 8]])

In [39]:
arr[1:, 1:3]

array([[ 6,  7],
       [10, 11]])

In [51]:
## Modify array elements

arr[0,0] = 1011
print(arr)

[[1011    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]


In [58]:
arr[1:2,0:2] = [50, 60]
print(arr)

[[ 1  2  3  4]
 [50 60  7  8]
 [ 9 10 11 12]]


In [3]:
## statistical concepts -- Normalization
## to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

# calculate mean and standard deviation

mean = np.mean(data)
std_dev = np.std(data)

## normalize the data

normalized_data = (data - mean)/std_dev
print("Normalized data : ", normalized_data)

Normalized data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [4]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean = np.mean(data)
print("Mean: ", mean)

# median
median = np.median(data)
print("Median: ", median)

# standard deviation
std_dev = np.std(data)
print("Standard deviation : ", std_dev)

# Variance
variance = np.var(data)
print("Variance: ",variance)



Mean:  5.5
Median:  5.5
Standard deviation :  2.8722813232690143
Variance:  8.25


In [14]:
## Logical operations

data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data <= 8)]


array([5, 6, 7, 8])

### Practice set

In [15]:
'''
Beginner: Basics & Arrays

Create a 1D array of integers from 10 to 50 with a step of 5.

Create a 3×3 matrix of all ones and another of all zeros.

Convert the Python list [1, 2, 3, 4, 5] into a NumPy array.

Find the shape, size, and data type of the array [ [1,2,3], [4,5,6] ].

Create an identity matrix of size 4×4.
'''

'\nBeginner: Basics & Arrays\n\nCreate a 1D array of integers from 10 to 50 with a step of 5.\n\nCreate a 3×3 matrix of all ones and another of all zeros.\n\nConvert the Python list [1, 2, 3, 4, 5] into a NumPy array.\n\nFind the shape, size, and data type of the array [ [1,2,3], [4,5,6] ].\n\nCreate an identity matrix of size 4×4.\n'

In [17]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [23]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
lst = [1, 2, 3, 4, 5]
arr = np.array(lst)
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [34]:
array = np.array([ [1,2,3], [4,5,6] ])
## shape
shape = np.shape(array)
print(shape)

## size
size = np.size(array)
print(size)

## data type
datatype = array.dtype
print(datatype)

(2, 3)
6
int64


Intermediate: Indexing, Slicing & Operations

Given arr = np.array([10, 20, 30, 40, 50]), extract elements greater than 25.

Create a 5×5 array with random integers from 1 to 50 and slice the middle 3×3 submatrix.

Multiply two 2×2 matrices element-wise and using matrix multiplication (np.dot).

Given a 1D array of 20 random numbers, reshape it into a 4×5 matrix.

Normalize the array [1, 2, 3, 4, 5] so that its values are between 0 and 1.

In [35]:
arr = np.array([10,20,30,40,50])
arr[arr>25]

array([30, 40, 50])

In [53]:
arr = np.random.randint(1,51,size = (5,5))
print(arr)

# slicing it into 3x3
sliced_arr = arr[1:4, 1:4]
print("Middle: ",sliced_arr)

[[23 13 50 35 14]
 [38 20 16  1  6]
 [ 8 21 24 49 24]
 [20 17 38  4 11]
 [40 39  1 15  3]]
Middle:  [[20 16  1]
 [21 24 49]
 [17 38  4]]


In [41]:
arr1 = np.array([[1,2],[4,5]])
arr2 = np.array([[3,7],[8,9]])

mat_multiply = np.dot(arr1,arr2)
print(mat_multiply)

[[19 25]
 [52 73]]


In [47]:
np.arange(1,21).reshape((4,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [48]:
arr = np.array([1,2,3,4,5])

mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr - mean)/std_dev
print(normalized_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
